/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/jobs/$jobId'
    | '/messages/$conversationId'
    | '/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/jobs/$jobId'
    | '/messages/$conversationId'
    | '/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/discover'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/settings'
    | '/jobs/$jobId'
    | '/messages/$conversationId'
    | '/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
